# Generated by Django 6.0.3 on 2026-03-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="comment",
        ),
    ]
