# Generated by Django 6.0.3 on 2026-03-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0002_rename_title_product_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
